import Navbar from "@/components/Navbar";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "@/context/authContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en" className={` h-full antialiased`}>
      <body className="h-screen gap-5 flex flex-col">
      <AuthProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className=" flex-1 p-4">{children}</div>
        </ThemeProvider>
      </AuthProvider>
        
      </body>
    </html>
  );
}
